### PR TITLE
Project kick-off.

### PR DESCRIPTION
**Pull request by 2e12**
Generate with bob.templates new basic module.

Closes https://github.com/4teamwork/bern.web/issues/1603

### CODE REVIEW

**Review by mbaechtold — APPROVED** [review]

**Comment by mbaechtold** [comment]
Hey @2e12, I have fixed the configuration of the GitHub checks. You may now merge this pull request.

**Review by mbaechtold — CHANGES_REQUESTED** [review]
Ooops, I just noticed that the `.gitignore` is missing because I ran buildout on my machine. 

Our template includes a `.gitignore` file (see https://github.com/4teamwork/bobtemplates.4teamwork/blob/master/bobtemplates/module/%2Bpackage.fullname%2B/.gitignore). 

Did you forget to commit it?

**Comment by 2e12** [comment]
> Ooops, I just noticed that the `.gitignore` is missing because I ran buildout on my machine.
> 
> Our template includes a `.gitignore` file (see https://github.com/4teamwork/bobtemplates.4teamwork/blob/master/bobtemplates/module/%2Bpackage.fullname%2B/.gitignore).
> 
> Did you forget to commit it?

I wasn't aware of that 😅 My bad. Next time I do better.

**Review by mbaechtold — APPROVED** [review]
Nice. Thank you!

**Pull request merged**
